name: Code Coverage

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov mcpi
        pip install google-generativeai 
        pip install -r requirements.txt
        
    - name: Generate coverage report
      run: |
        python -m pytest tests/test_agents.py --cov=Agents --cov-report=xml
        
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: gonzalogabrielfm/AdventuresInMinecraft


